using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Business_Layer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    public partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Business_Layer.Student", b =>
            {
                b.Property<int>("StudentId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));
                b.Property<string>("StudentCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("StudentName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Email")
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Status")
                    .HasColumnType("nvarchar(50)");
                b.Property<string>("PhoneNumber")
                    .HasColumnType("nvarchar(20)");
                b.Property<DateTime?>("DateOfBirth")
                    .HasColumnType("datetime2(7)");
                b.Property<string>("AvatarPath")
                    .HasColumnType("nvarchar(max)");
                b.Property<DateTime?>("LastLogin")
                    .HasColumnType("datetime2(7)");
                b.HasKey("StudentId");
                b.ToTable("Students");
            });
            modelBuilder.Entity("Business_Layer.Instructor", b =>
            {
                b.Property<int>("InstructorId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));
                b.Property<string>("InstructorName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<int>("Experience")
                    .IsRequired()
                    .HasColumnType("int");
                b.Property<string>("Email")
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("PhoneNumber")
                    .HasColumnType("nvarchar(20)");
                b.HasKey("InstructorId");
                b.ToTable("Instructors");
            });
            modelBuilder.Entity("Business_Layer.LifeSkillCourse", b =>
            {
                b.Property<int>("CourseId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));
                b.Property<string>("CourseName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<int>("InstructorId")
                    .HasColumnType("int")
                    .IsRequired();
                b.Property<DateTime>("StartDate")
                    .HasColumnType("datetime2(7)");
                b.Property<DateTime>("EndDate")
                    .HasColumnType("datetime2(7)");
                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");
                b.Property<int>("MaxStudents")
                    .HasColumnType("int");
                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)");
                b.Property<string>("Status")
                    .HasColumnType("nvarchar(50)");
                b.HasKey("CourseId");
                b.HasIndex("InstructorId");
                b.ToTable("LifeSkillCourses");
            });
            modelBuilder.Entity("Business_Layer.Enrollment", b =>
            {
                b.Property<int>("EnrollmentId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));
                b.Property<int>("StudentId")
                    .HasColumnType("int")
                    .IsRequired();
                b.Property<int>("CourseId")
                    .HasColumnType("int")
                    .IsRequired();
                b.Property<bool>("CompletionStatus")
                    .HasColumnType("bit");
                b.Property<DateTime>("CompletionDate")
                    .HasColumnType("datetime2(7)");
                b.HasKey("EnrollmentId");
                b.HasIndex("StudentId");
                b.HasIndex("CourseId");
                b.ToTable("Enrollments");
            });
            modelBuilder.Entity("Business_Layer.Assessment", b =>
            {
                b.Property<int>("AssessmentId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentId"));
                b.Property<int>("CourseId")
                    .HasColumnType("int")
                    .IsRequired();
                b.Property<string>("AssessmentName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<int>("MaxScore")
                    .IsRequired()
                    .HasColumnType("int");  
                b.Property<DateTime>("DueDate")
                    .IsRequired()
                    .HasColumnType("datetime2(7)");
                b.Property<string>("AssessmentType")
                    .HasColumnType("nvarchar(50)");
                b.Property<string>("Instructions")
                    .HasColumnType("nvarchar(max)");
                b.HasKey("AssessmentId");
                b.HasIndex("CourseId");
                b.ToTable("Assessments");
            });
            modelBuilder.Entity("Business_Layer.AssessmentResult", b =>
            {
                b.Property<int>("AssessmentResultId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentResultId"));
                b.Property<int>("AssessmentId")
                    .HasColumnType("int")
                    .IsRequired();
                b.Property<int>("StudentId")
                    .HasColumnType("int")
                    .IsRequired();
                b.Property<decimal>("Score")
                    .IsRequired()
                    .HasColumnType("decimal(4,1)");
                b.Property<DateTime>("SubmissionDate")
                    .HasColumnType("datetime2(7)");
                b.HasKey("AssessmentResultId");
                b.HasIndex("StudentId");
                b.HasIndex("AssessmentId");
                b.ToTable("AssessmentResults");
            });
            modelBuilder.Entity("Business_Layer.Notification", b =>
            {
                b.Property<int>("NotificationId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));
                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<int>("StudentId")
                    .HasColumnType("int")
                    .IsRequired();
                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2(7)");
                b.HasKey("NotificationId");
                b.HasIndex("StudentId");
                b.ToTable("Notifications");
            });
            modelBuilder.Entity("Business_Layer.CourseMaterial", b =>
            {
                b.Property<int>("MaterialId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));
                b.Property<int>("CourseId")
                    .HasColumnType("int")
                    .IsRequired();
                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("FilePath")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<DateTime>("UploadDate")
                    .HasColumnType("datetime2(7)");
                b.HasKey("MaterialId");
                b.HasIndex("CourseId");
                b.ToTable("CourseMaterials");
            });
            modelBuilder.Entity("Business_Layer.Feedback", b =>
            {
                b.Property<int>("FeedbackId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));
                b.Property<int>("StudentId")
                    .HasColumnType("int")
                    .IsRequired();
                b.Property<int>("CourseId")
                    .HasColumnType("int")
                    .IsRequired();
                b.Property<int>("Rating")
                    .IsRequired()
                    .HasColumnType("int");
                b.Property<string>("Comment")
                    .HasColumnType("nvarchar(max)");
                b.Property<DateTime>("FeedbackDate")
                    .HasColumnType("datetime2(7)");
                b.HasKey("FeedbackId");
                b.HasIndex("StudentId");
                b.HasIndex("CourseId");
                b.ToTable("Feedbacks");
            });
            modelBuilder.Entity("Business_Layer.Certificate", b =>
            {
                b.Property<int>("CertificateId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificateId"));
                b.Property<int>("StudentId")
                    .HasColumnType("int")
                    .IsRequired();
                b.Property<int>("CourseId")
                    .HasColumnType("int")
                    .IsRequired();
                b.Property<DateTime>("IssueDate")
                    .HasColumnType("datetime2(7)");
                b.Property<string>("CertificateCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)");
                b.Property<string>("FilePath")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.HasKey("CertificateId");
                b.HasIndex("StudentId");
                b.HasIndex("CourseId");
                b.ToTable("Certificates");
            });
            modelBuilder.Entity("Business_Layer.CourseSchedule", b =>
            {
                b.Property<int>("ScheduleId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));
                b.Property<int>("CourseId")
                    .HasColumnType("int")
                    .IsRequired();
                b.Property<DateTime>("SessionDate")
                    .HasColumnType("datetime2(7)");
                b.Property<TimeSpan>("StartTime")
                    .HasColumnType("time(7)");
                b.Property<TimeSpan>("EndTime")
                    .HasColumnType("time(7)");
                b.Property<string>("Room")
                    .HasColumnType("nvarchar(50)");
                b.HasKey("ScheduleId");
                b.HasIndex("CourseId");
                b.ToTable("CourseSchedules");
            });
            modelBuilder.Entity("Business_Layer.ActivityLog", b =>
            {
                b.Property<int>("LogId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityLogId"));
                b.Property<int>("UserId")
                    .HasColumnType("int")
                    .IsRequired();
                b.Property<string>("Action")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<DateTime>("Timestamp")
                    .HasColumnType("datetime2(7)");
                b.HasKey("LogId");
                b.HasIndex("UserId");
                b.ToTable("ActivityLogs");
            });
            modelBuilder.Entity("Business_Layer.Payment", b =>
            {
                b.Property<int>("PaymentId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));
                b.Property<int>("StudentId")
                    .HasColumnType("int")
                    .IsRequired();
                b.Property<int>("CourseId")
                    .HasColumnType("int")
                    .IsRequired();
                b.Property<decimal>("Amount")
                    .HasColumnType("decimal(18,2)");
                b.Property<DateTime>("PaymentDate")
                    .HasColumnType("datetime2(7)");
                b.Property<string>("Status")
                    .HasColumnType("nvarchar(50)");
                b.HasKey("PaymentId");
                b.HasIndex("StudentId");
                b.HasIndex("CourseId");
                b.ToTable("Payments");
            });
        }
    }
}
